In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('IRIS.csv')

In [3]:
X = dataset.iloc[:,:4].values
y = dataset['species'].values
dataset.head(5)

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [6]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [7]:
y_pred = classifier.predict(X_test) 
y_pred

array(['Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor'], dtype='<U15')

In [10]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import accuracy_score 
print("Confusion matrix: \n",cm)
print ("\nAccuracy : ", accuracy_score(y_test, y_pred)*100,"%")

Confusion matrix: 
 [[ 8  0  0]
 [ 0 11  0]
 [ 0  1 10]]

Accuracy :  96.66666666666667 %


In [11]:
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values Predicted Values
0   Iris-versicolor  Iris-versicolor
1       Iris-setosa      Iris-setosa
2   Iris-versicolor  Iris-versicolor
3    Iris-virginica   Iris-virginica
4   Iris-versicolor  Iris-versicolor
5   Iris-versicolor  Iris-versicolor
6    Iris-virginica   Iris-virginica
7    Iris-virginica   Iris-virginica
8       Iris-setosa      Iris-setosa
9   Iris-versicolor  Iris-versicolor
10      Iris-setosa      Iris-setosa
11      Iris-setosa      Iris-setosa
12   Iris-virginica   Iris-virginica
13   Iris-virginica   Iris-virginica
14      Iris-setosa      Iris-setosa
15      Iris-setosa      Iris-setosa
16  Iris-versicolor  Iris-versicolor
17   Iris-virginica   Iris-virginica
18   Iris-virginica   Iris-virginica
19      Iris-setosa      Iris-setosa
20  Iris-versicolor  Iris-versicolor
21  Iris-versicolor  Iris-versicolor
22  Iris-versicolor  Iris-versicolor
23   Iris-virginica   Iris-virginica
24   Iris-virginica  Iris-versicolor
25   Iris-virginica   Iris-virginica
26   Iris-virginica   Iris-virginica
27  Iris-versicolor  Iris-versicolor
28      Iris-setosa      Iris-setosa
29  Iris-versicolor  Iris-versicolor

In [13]:
print("For class 1\n")
print("Accuracy: 100%, Precision: 1.0, Recall: 1.0")
print("\nFor class 2\n")
print("Accuracy: 96.6%, Precision: 1.0, Recall: 0.92")
print("\nFor class 3\n")
print("Accuracy: 96.6%, Precision: 0.91, Recall: 1.0")

For class 1

Accuracy: 100%, Precision: 1.0, Recall: 1.0

For class 2

Accuracy: 96.6%, Precision: 1.0, Recall: 0.92

For class 3

Accuracy: 96.6%, Precision: 0.91, Recall: 1.0
